name: Eth.swift Test

on:
  push:

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: swift-actions/setup-swift@v2
      with:
        swift-version: "5.10"

    - name: Cache SwiftPM
      id: cache-swiftpm
      uses: actions/cache@v2
      with:
        path: |
          ~/.swiftpm
          .build
        key: ${{ runner.os }}-swiftpm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-swiftpm-

    - name: Build and Test
      run: swift test | xcbeautify --renderer github-actions
