name: Eth.swift Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: swift-actions/setup-swift@v2
      with:
        swift-version: "5.10"

    - name: Cache SwiftPM
      uses: actions/cache@v4
      with:
        path: |
          ~/.swiftpm
          .build
        key: ${{ runner.os }}-swiftpm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-swiftpm-

    - name: Build and Test
      run: swift test | xcbeautify --renderer github-actions
